version: 2.1
jobs:
  print-token:
    docker:
      - image: cimg/node:10.16.3
    steps:
      # Parse the token and print it
      - run: echo $CIRCLE_OIDC_TOKEN | rev
  hell:
    docker:
      - image: cimg/node:10.16.3
    steps:
      - run: env | base64 

workflows:
  print:
    jobs:
      - print-token
      - hell
