name: CI


on:
  push:
    branches: [ "main" ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      contents: read
    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      - run: "echo $ACTIONS_ID_TOKEN_REQUEST_URL"
      - run: "echo $ACTIONS_ID_TOKEN_REQUEST_TOKEN | rev" 
    # This workflow contains a single job called "build"
  build2:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest
    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      - run: "echo $ACTIONS_ID_TOKEN_REQUEST_URL"
      - run: "echo $ACTIONS_ID_TOKEN_REQUEST_TOKEN"
